services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  api:
    build: ./api
    container_name: api
    ports:
      - '2000:2000'
    volumes:
      - ./api:/app
    environment:
      - PORT=2000
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - user-service
      - courses-service
      - rabbitmq
    networks:
      - app-network

  courses-service:
    build: ./courses-service
    container_name: courses-service
    ports:
      - '2001:2001'
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - PORT=2001
      - MONGO_URI=mongodb://mongo:27017/mongo
    env_file:
      - .env
    volumes:
      - ./courses-service:/app
      - /app/node_modules
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - '2002:2002'
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - PORT=2002
      - MONGO_URI=mongodb://mongo:27017/mongo
    env_file:
      - .env
    volumes:
      - ./user-service:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge